### ISSUE TITLE
can we do predictive HPA & sudden spike auto scaling on EKS using this ?

### ISSUE THREAD

**Issue by nandhyala** [jthomperoo/predictive-horizontal-pod-autoscaler#26]

**Comment by nandhyala** [comment]
@jthomperoo 

can we do predictive HPA & sudden spike auto scaling on EKS using this ?

**Comment by jthomperoo** [comment]
Hi, yes that would be possible, this Predictive Autoscaler and the Custom Pod Autoscaler Framework in general has been tested on EKS, so it should work. The difficulty here is understanding which model to apply, and tuning that model. If you haven't seen it already, I wrote an [article on this which might be helpful](https://jamiethompson.me/posts/Evaluating-Predictive-Autoscaling-Kubernetes/). So I can help you a bit further, could you maybe explain a bit of your use case?

**Comment by nandhyala** [comment]
Thanks @jthomperoo for helping me on this,I went through  you article and looks good & interesting ,looking for some more details from you to fit in our use case.

Below is my use case:

1) We are running 500+ GPU EC2 machine on EKS for object detection using machine learning on prod.
2) For auto scaling GPU nodes on EKS we are using custom lifetime (each process average taking time) metrics todo autoscaling ,Same lifetime metrics doing for 2k & 4k video frames it will vary lifetime value depends on frame.
3)We are pushing lifetime metrics into cloudwatch using statsd.
4)From cloudwatch we pulling metrics into EKS using cloudwatch external plugin and passing to HPA for autoscaling.
5) Every thing is working fine but when peak load start GPU pods takes time average 6 mins running status so that the lifetime metrics going high in couple of seconds (example :target value from 500 to 2.5k within 10 secs ) and suddenly pod replicas going to 200+ from 20 .
6)To avoid 5 step issue i want launch proactive 10 mins before peak starts  so that i can avoid from 500 to 2.5k within 10 secs & launching pods to 200 unnesary cost on gpu machines.
7)In same metric i want use proactive + reactive methods so that i can avoid sudden spike issue also on prod eks cluster.

Can you please go through my use case and help me how can fit your Predictive Autoscaler and the Custom Pod Autoscaler in our case and need your help if any thing fit for us ,So i will test in lower environments and take it forward to prod.

Thanks !

**Comment by jthomperoo** [comment]
Great, thanks for sharing such an interesting use case!

I think the Predictive Horizontal Pod Autoscaler (PHPA) could be useful to you here, it can be dropped in place instead of the Horizontal Pod Autoscaler (HPA) - with models configured for prediction.

So just to clarify a few things:

1. The GPU pods take 6 minutes after starting before they are usable and can process data?
2. Is the peak load predictable and repeated (e.g. every day at 3:00pm)?

If this is a predicted and repeated load, you could apply a [Holt Winters model](https://predictive-horizontal-pod-autoscaler.readthedocs.io/en/latest/user-guide/models/#holt-winters-time-series-prediction) which allows seasonal prediction based on standard K8s HPA metrics (with support for custom metrics). This would be the simplest option; however it would again require some tuning, which should be data driven. I have written a [small experiment showing this working](https://jamiethompson.me/posts/Evaluating-Predictive-Autoscaling-Kubernetes/).

![image](https://user-images.githubusercontent.com/6690498/80369111-a0525680-8885-11ea-94f1-93457f087f4a.png)

As you can see in this experiment it has led to a reduction in some of the average latency/maximum latency peaks, but could be much more effective with better tuning.

To start with this, I would begin by collecting all of the lifetime metrics you are using for a 24/48 hour period, and then fit this using a Holt-Winters algorithm to determine the best tuning values for alpha, beta, and gamma tuning values.

However this approach may not be the most effective, and the PHPA may not be the best choice for your use case - in this case building your own autoscaler may be the best tactic, and the Custom Pod Autoscaler Framework makes that a lot easier. Initially I would try the tuning and applying the PHPA, if this doesn't see acceptable improvement I would look at building a custom autoscaler.

Hope that helps, thanks for the feedback!

**Comment by nandhyala** [comment]
@jthomperoo ,Thanks for explaining in details,First we can try with PHPA but still have couple of questions on this approach. 

a) In PHPA how it will reactive if there is any sudden spike due to bug on software or OS level issues ..etc ...?
b) How can i pass custom cloud watch metrics into PHPA and how it will do preditve ?
c) We have last One week of lifetime metrics are available  on cloud watch ,Can we use these metrics bcz i see sudden spike on graphs during peak hours ?
d) We are doing HPA based  average aggregation on 60 sec if it reduce to less then 30 secs help us to reduce sudden spikes on metrics & launching pods ?
 
Below are my comments :
1) The GPU pods take 6 minutes after starting before they are usable and can process data?
--> its takes time for container to read status bcz at os level attachment related to GPU,There is no data process.

2) Is the peak load predictable and repeated (e.g. every day at 3:00pm)?
--> Every day constant load during Business hours (From 6:30 AM PST to 3:30 PM PST) load will increase gradually .

Thanks !

**Comment by jthomperoo** [comment]
Sorry for the delay in my response, I'm super busy at the moment! Here's some answers to your questions:

a) The PHPA still uses the HPA logic behind the scenes, so if there is a sudden spike that occurs it will still react to it in the same way as the HPA would - if it is suddenly at much higher load than predicted the predictive models will be overridden and the HPA will take over directly.

b) You can pass metrics into the PHPA in the exact same way as you do to the HPA, you can actually copy and paste your HPA configuration into a PHPA deployment file, it will function the same way using metrics. If you are already running the HPA, the PHPA will work without extra configuration around metrics.

c) That's great, a week of lifetime metrics would be good to use to tune your autoscaler, this process is a bit manual and would require feeding these metrics into a holt-winters model and manually tuning to see how predictions fit and if it suits your use case.

d) I'm not 100% sure what you are asking here, but if you are asking if reducing the HPA sync period would help reduce spikes and pod provisioning time, I think it would - at least making the system more responsive; the only thing is on EKS you can't adjust this value on the normal HPA as you need master node SSH access - but with the CPA or PHPA you can configure that at deploy time.

Hope that helps a bit!

**Comment by nandhyala** [comment]
Thanks @jthomperoo for you valuable inputs ,I will try to setup on non-prod eks cluster and get back you if i face any issues

**Comment by shubhamitc** [comment]
@jthomperoo, it seems like you are expecting to have predefined values for alpha, beta, and gamma. I suppose we should try to fetch optimize values for these parameters, probably using a grid search. Let me know your thoughts.

**Comment by jthomperoo** [comment]
That's a really interesting idea, I hadn't thought of that. So perhaps a solution to this would be allowing some kind of 'hook' that would allow fetching these values at runtime? This would allow some logic to determine these parameters, which could be making an HTTP request, or running a simple python script. Do you think this would address this issue?

I have opened a new issue to track this here:
#27

**Comment by jthomperoo** [comment]
OK I think this issue is OK to close for now, if there's any issues anyone has feel free to comment/reopen this.
