### ISSUE TITLE
failed to get resource metric

### ISSUE THREAD

**Issue by MarahAbu** [jthomperoo/predictive-horizontal-pod-autoscaler#60]
Hi, I see this error in cpa pod logs: "Shell command failed, stderr: 2022/01/30 13:29:20 invalid metrics (1 invalid out of 1), first error is: failed to get resource metric: unable to get metrics for resource cpu: no metrics returned from resource metrics API"

1. Deploy latest phpa

**Additional context**
Can you please check if you have this error in your logs and if it really affects the phpa?

**Comment by jthomperoo** [comment]
Hi, thanks for raising this - sorry for the slow response, haven't been able to find recently to work on these projects.

This error is fine if the PHPA eventually starts working, this often happens when the resource you are scaling has not provided the metrics server with any metrics yet, so it will report no metrics. In a normal system this wouldn't happen (and isn't anything to worry about) since normally the resources are long running and will be providing metrics to the metrics server. The same error occurs behind the scenes for the normal Kubernetes Horizontal Pod Autoscaler.

Hope this helps!

If I've misunderstood/there's a further problem here, feel free to re-open this issue.

**Comment by MarahAbu** [comment]
Hi, I'm back on working on this but still can't proceed because of this issue, tried a few things but still it doesn't scale any pods even under a huge load, i would really appreciate it if we could have a demo or something to help.
thanks in advance
